language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: PlNCaKmWRS+R14pjAUPt+yKqsxMyjjrs0JYoNHgRIvSWtvXsvpLV9JFHILPrUTNk2gJzNeNEl0bRRRk5C1UfacHQEQ129LJi8JudmDs7mphKe0edh/PSNG1MjWdyZeeF4NTywBPElTdUb4rR2mrOuRgfL4LvPM5vnrShUXWM6oM=
  file:
    - 'nlcst-emoticon-modifier.js'
    - 'nlcst-emoticon-modifier.min.js'
  on:
    tags: true
